//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sarh_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sarh_usuario()
        {
            this.Sarh_CentroCostoxUsurio = new HashSet<Sarh_CentroCostoxUsurio>();
            this.Sarh_familiarxusuario = new HashSet<Sarh_familiarxusuario>();
        }
    
        public decimal id_usuario_pk { get; set; }
        public Nullable<short> id_tipodocumento_fk { get; set; }
        public decimal us_numerodocumento { get; set; }
        public string us_nombre1 { get; set; }
        public string us_nombre2 { get; set; }
        public string us_apellido1 { get; set; }
        public string us_apellido2 { get; set; }
        public Nullable<decimal> us_login_base { get; set; }
        public string us_telefonoppal { get; set; }
        public string us_telefonosecundario { get; set; }
        public string us_celular { get; set; }
        public string us_email { get; set; }
        public string us_direccion { get; set; }
        public string us_barrio { get; set; }
        public Nullable<System.DateTime> us_fnacimiento { get; set; }
        public string us_lugarnacimiento { get; set; }
        public Nullable<int> us_numhijos { get; set; }
        public Nullable<short> id_estadocivil_fk { get; set; }
        public Nullable<short> us_idrh_fk { get; set; }
        public Nullable<int> id_eps_fk { get; set; }
        public Nullable<int> id_afp_fk { get; set; }
        public string us_tallacamisa { get; set; }
        public string us_tallapantalon { get; set; }
        public string us_tallachaqueta { get; set; }
        public string us_tallacalzado { get; set; }
        public short id_estado_fk { get; set; }
        public Nullable<short> id_sede_fk { get; set; }
        public Nullable<short> id_perfil_fk { get; set; }
        public Nullable<decimal> id_cargo_fk { get; set; }
        public Nullable<short> id_empleador_fk { get; set; }
        public Nullable<short> id_tipocontrato_fk { get; set; }
        public Nullable<short> id_tipojornada_fk { get; set; }
        public Nullable<System.DateTime> us_fechainicio { get; set; }
        public Nullable<System.DateTime> us_fechaterminacion { get; set; }
        public Nullable<System.DateTime> fcreacion { get; set; }
        public Nullable<decimal> us_usucre_fk { get; set; }
        public Nullable<decimal> id_coord { get; set; }
        public System.Guid rowguid { get; set; }
        public string us_empresa { get; set; }
        public Nullable<decimal> us_costos { get; set; }
        public string us_idsexo_fk { get; set; }
        public string us_usuario { get; set; }
        public string us_pwd { get; set; }
        public string us_PorcentajeVariable { get; set; }
        public string us_Marca { get; set; }
        public Nullable<int> us_IdVariable_fk { get; set; }
        public Nullable<decimal> us_IdJefe { get; set; }
        public Nullable<int> us_IdBandera_fk { get; set; }
        public Nullable<decimal> us_login_Sec { get; set; }
        public Nullable<int> id_clasecontrato_fk { get; set; }
        public Nullable<decimal> id_DireccionFisica_pk { get; set; }
        public string us_correo_personal { get; set; }
        public Nullable<bool> us_licencia_conduccion { get; set; }
        public Nullable<bool> us_vehiculo_moto { get; set; }
        public Nullable<bool> us_vehiculo_automovil { get; set; }
        public string us_extension { get; set; }
        public Nullable<bool> us_Disponibilidad_viajar { get; set; }
        public Nullable<bool> us_Disponibilidad_traslado { get; set; }
        public Nullable<bool> us_Madre_Cabeza_Hogar { get; set; }
        public Nullable<bool> us_afrodescendiente { get; set; }
        public Nullable<bool> us_enfermedad_profesional { get; set; }
        public Nullable<bool> us_desplazamiento { get; set; }
        public Nullable<bool> us_discapacitado { get; set; }
        public Nullable<bool> us_reintegracion { get; set; }
        public Nullable<bool> us_aprendiz_sena { get; set; }
        public string us_lugarexpedicion { get; set; }
        public Nullable<int> us_pais_nacimiento { get; set; }
        public Nullable<int> us_nacionalidad { get; set; }
        public Nullable<decimal> us_libretaMilitarNo { get; set; }
        public Nullable<int> us_categoriaSisben { get; set; }
        public Nullable<int> us_categorialicencia { get; set; }
        public Nullable<int> us_ciudad_direccion { get; set; }
        public string us_conocimiento_sist { get; set; }
        public string us_direccion_partes { get; set; }
        public Nullable<bool> us_estadocargue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sarh_CentroCostoxUsurio> Sarh_CentroCostoxUsurio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sarh_familiarxusuario> Sarh_familiarxusuario { get; set; }
    }
}
