//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sarh_familiarxusuario
    {
        public decimal id_familiar_pk { get; set; }
        public Nullable<decimal> fam_idUsuario_fk { get; set; }
        public string fam_NombreCompleto { get; set; }
        public string fam_DocumentoFamiliar { get; set; }
        public Nullable<int> fam_Parentesco_Familiar { get; set; }
        public Nullable<System.DateTime> fam_fcreacion { get; set; }
        public System.Guid rowguid { get; set; }
        public decimal fam_idusucreador_fk { get; set; }
        public Nullable<int> fam_ocupacion_fk { get; set; }
        public string fam_empresa { get; set; }
        public Nullable<decimal> fam_telefono { get; set; }
        public string fam_depende { get; set; }
    
        public virtual Sarh_usuario Sarh_usuario { get; set; }
    }
}
